### ISSUE TITLE
torch.nn.modules.module.ModuleAttributeError: 'YOLOLayer' object has no attribute 'grid'

### ISSUE THREAD

**Issue by KevinPatel04** [ocean-data-factory-sweden/koster_ml#1]
Hi @jannesgg, I am getting this error while using your model implementation with pre-trained weights of tiny-yolov3.

`torch.nn.modules.module.ModuleAttributeError: 'YOLOLayer' object has no attribute 'grid'`

Please can you tell me the solution to this problem?

--
Thanking you,
Kevin

**Comment by jannesgg** [comment]
Hi @KevinPatel04,

I have not encountered this issue before but it seems to have been raised here https://github.com/ultralytics/yolov3/issues/1173 as well. If you could provide more information, I could try to investigate this further. 

Thanks,
Jannes

**Comment by jannesgg** [comment]
Closing the issue due to inactivity. Re-open should you need to.
